image: Ubuntu2004  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  - chmod +x gradlew

build_script:
  # Запускаем автотесты
  - ./gradlew test --info